name: Build for Windows

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: windows-2022

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "12"
            - run: npm ci
            - run: echo "${env:path};${env:wix}bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
            - run: npm run make-windows
            - uses: actions/upload-artifact@v2
              with:
                  name: windows-msi-${{ github.sha }}
                  path: out/make/wix/x64/CurrentTask.msi
            - uses: actions/upload-artifact@v2
              with:
                  name: windows-zip-${{ github.sha }}
                  path: out/make/zip/win32/x64/*.zip
