name: Release Drafter

on:
    push:
        branches: [master]

jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            # configured in .github/release-drafter.yml
            - uses: release-drafter/release-drafter@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
